# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.4.19.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.1.33"
  - "7.2.31"
  - "7.3.18"
  - "7.4.6"
image:
  composer:
    version: "1.10.6"
