# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.5.1.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "released"
php:
  - "7.1.33"
  - "7.2.30"
  - "7.3.17"
  - "7.4.5"
image:
  composer:
    version: "1.10.6"
