# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.6.0-beta.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.2.34"
  - "7.3.25"
  - "7.4.13"
  - "8.0.0"
image:
  composer:
    version: "2.0.8"
