# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.7.0.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "released"
php:
  - "7.2.34"
  - "7.3.29"
  - "7.4.21"
  - "8.0.8"
image:
  composer:
    version: "2.1.3"
