# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.8.10.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.2.34"
  - "7.3.33"
  - "7.4.29"
  - "8.0.19"
  - "8.1.6"
image:
  composer:
    version: "2.2.12"
