# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.8.3.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.2.34"
  - "7.3.33"
  - "7.4.26"
  - "8.0.13"
  - "8.1.0"
image:
  composer:
    version: "2.1.14"
