# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:5.0.0.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "8.0.21"
  - "8.1.8"
image:
  composer:
    version: "2.3.10"
