name: Build Versioned Images

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'
      - '[4-9].[0-9]+.[0-9]+-?[a-zA-Z]**'

jobs:
  build_versioned_images:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'swoole/docker-swoole' }}
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]

    name: The image for PHP ${{ matrix.php }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set output parameters
        id: params
        run: |
          echo ::set-output name=branch_name::${GITHUB_REF##*/}
          branch_name=${GITHUB_REF##*/}
          major_version=${branch_name%.*}
          if egrep -q '^status\:\s*"under development"\s*($|\#)' "$(pwd)/config/${branch_name}.yml" ; then
            if [ ${{ matrix.php }} == '8.0' ] ; then
              if [ ${major_version} == '4.8' ] ; then
                echo "::set-output name=full_names::phpswoole/swoole:${branch_name}-php${{ matrix.php }},phpswoole/swoole:${major_version}-php${{ matrix.php }},phpswoole/swoole:${major_version},phpswoole/swoole:latest"
              else
                echo "::set-output name=full_names::phpswoole/swoole:${branch_name}-php${{ matrix.php }},phpswoole/swoole:${major_version}-php${{ matrix.php }},phpswoole/swoole:${major_version}"
              fi
            else
              if [ ${{ matrix.php }} == '7.4' ] && [ ${major_version} == '4.4' ] ; then
                echo "::set-output name=full_names::phpswoole/swoole:${branch_name}-php${{ matrix.php }},phpswoole/swoole:${major_version}-php${{ matrix.php }},phpswoole/swoole:${major_version}"
              else
                echo "::set-output name=full_names::phpswoole/swoole:${branch_name}-php${{ matrix.php }},phpswoole/swoole:${major_version}-php${{ matrix.php }}"
              fi
            fi
          else
              echo "::set-output name=full_names::phpswoole/swoole:${branch_name}-php${{ matrix.php }}"
          fi

      -
        name: Build and push Docker image phpswoole/swoole:${{ steps.params.outputs.branch_name }}-php${{ matrix.php }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/${{ steps.params.outputs.branch_name }}/php${{ matrix.php }}/cli/Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          push: true
          tags: ${{ steps.params.outputs.full_names }}

      -
        name: Image digest of phpswoole/swoole:${{ steps.params.outputs.branch_name }}-php${{ matrix.php }}
        run: echo ${{ steps.docker_build.outputs.digest }}
