name: Build Versioned Images

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'

jobs:
  buid_versioned_images:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'swoole/docker-swoole' }}
    strategy:
      fail-fast: true
      matrix:
        php: ["7.1", "7.2", "7.3", "7.4", "8.0"]

    name: The image for PHP ${{ matrix.php }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Get/set branch name
        id: vars
        run: echo ::set-output name=branch_name::${GITHUB_REF##*/}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image phpswoole/swoole:${{ steps.vars.outputs.branch_name }}-php${{ matrix.php }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/${{ steps.vars.outputs.branch_name }}/php${{ matrix.php }}/cli/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: phpswoole/swoole:${{ steps.vars.outputs.branch_name }}-php${{ matrix.php }}

      -
        name: Image digest of phpswoole/swoole:${{ steps.vars.outputs.branch_name }}-php${{ matrix.php }}
        run: echo ${{ steps.docker_build.outputs.digest }}
