name: Build Latest PHP 8.0 arm64v8 Images

on:
  workflow_dispatch:

env:
  PHP_VERSION: "8.0"

jobs:
  buid_latest_images:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'swoole/docker-swoole' }}
    strategy:
      fail-fast: true

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Get/set PHP version
        id: vars
        run: echo ::set-output name=php_version::${PHP_VERSION}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt
          platforms: arm64

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image phpswoole/swoole:php8.0-arm64v8
        id: docker_build_php80
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/latest/arm64v8/php${{ steps.vars.outputs.php_version }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: phpswoole/swoole:php8.0-arm64v8

      -
        name: Image digest of phpswoole/swoole:php8.0-arm64v8
        run: echo ${{ steps.docker_build_php80.outputs.digest }}

      -
        name: Build and push Docker image phpswoole/swoole:php8.0-arm64v8-dev
        id: docker_build_php80_dev
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/latest/arm64v8/php${{ steps.vars.outputs.php_version }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: phpswoole/swoole:php8.0-arm64v8-dev
          build-args: DEV_MODE=true
      -
        name: Image digest of phpswoole/swoole:php8.0-arm64v8-dev
        run: echo ${{ steps.docker_build_php80_dev.outputs.digest }}
