name: Build Latest PHP 7.4 Alpine Images

on:
  schedule:
    - cron: '47 4 * * *'
  workflow_dispatch:

env:
  PHP_VERSION: "7.4"

jobs:
  buid_latest_images:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'swoole/docker-swoole' }}
    strategy:
      fail-fast: true

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Get/set PHP version
        id: vars
        run: echo ::set-output name=php_version::${PHP_VERSION}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image phpswoole/swoole:php7.4-alpine
        id: docker_build_php74_alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/latest/alpine/php${{ steps.vars.outputs.php_version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: phpswoole/swoole:php7.4-alpine,phpswoole/swoole:latest-alpine

      -
        name: Image digest of phpswoole/swoole:php7.4-alpine
        run: echo ${{ steps.docker_build_php74_alpine.outputs.digest }}
