name: Build Versioned Dev Images

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'
      - '[4-9].[0-9]+.[0-9]+-?[a-zA-Z]**'

jobs:
  build_versioned_dev_images:
    runs-on: ubuntu-latest
    if: github.repository == 'swoole/docker-swoole'
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]

    name: The dev image for PHP ${{ matrix.php }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set output parameters
        id: params
        run: |
          set -ex

          echo "{branch_name}={${GITHUB_REF##*/}}" >> $GITHUB_OUTPUT
          branch_name=${GITHUB_REF##*/}
          if egrep -q '^status\:\s*"under development"\s*($|\#)' "$(pwd)/config/${branch_name}.yml" ; then
            major_version=${branch_name%.*}
            if [ ${{ matrix.php }} == '8.1' ] ; then
              if [ ${major_version} == '5.0' ] ; then
                echo "{full_names}={phpswoole/swoole:${branch_name}-php${{ matrix.php }}-dev,phpswoole/swoole:${major_version}-php${{ matrix.php }}-dev,phpswoole/swoole:${major_version}-dev,phpswoole/swoole:latest-dev}" >> $GITHUB_OUTPUT
              else
                echo "{full_names}={phpswoole/swoole:${branch_name}-php${{ matrix.php }}-dev,phpswoole/swoole:${major_version}-php${{ matrix.php }}-dev,phpswoole/swoole:${major_version}-dev}" >> $GITHUB_OUTPUT
              fi
            else
              echo "{full_names}={phpswoole/swoole:${branch_name}-php${{ matrix.php }}-dev,phpswoole/swoole:${major_version}-php${{ matrix.php }}-dev}" >> $GITHUB_OUTPUT
            fi
          else
            echo "{released_already}={true}" >> $GITHUB_OUTPUT
          fi

      -
        name: Build and push Docker image phpswoole/swoole:${{ steps.params.outputs.branch_name }}-php${{ matrix.php }}-dev
        id: docker_build
        if: steps.params.outputs.released_already != 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/${{ steps.params.outputs.branch_name }}/php${{ matrix.php }}/cli/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          push: true
          tags: ${{ steps.params.outputs.full_names }}
          build-args: DEV_MODE=true
